# Generated by Django 5.1.6 on 2025-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="default_pic/blank-profile-picture.png",
                upload_to="profile_images/",
            ),
        ),
    ]
