# Generated by Django 5.1.6 on 2025-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                default="default_pic/blank-profile-picture.png",
                upload_to="profile_images/",
            ),
        ),
    ]
