# Generated by Django 5.1.6 on 2025-02-17 07:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images/")),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("no_of_likes", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
