# Generated by Django 5.1.6 on 2025-02-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=100)),
            ],
        ),
    ]
