# Generated by Django 5.1.6 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0007_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
